name: Run scrapev2.py

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/run-python.yml"
      - "requirements.txt"
      - "scrapev2.py"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Google Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show Chrome version
        run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run under a virtual display in case your script didn't set headless
      - name: Run script
        run: |
          xvfb-run -a python scrapev2.py

      # Optional: upload CSVs your script produces
      - name: Upload CSV output (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            export_combined.csv
            *.csv
